version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: brev_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=brevdb
    volumes:
      - pgdata:/bitnami/postgresql
    
volumes:
  pgdata: